CREATE TABLE my_users (
    id NUMBER GENERATED BY DEFAULT as IDENTITY(START with 1 INCREMENT by 1 NOCACHE),
    login VARCHAR2(50) NOT NULL,
    password VARCHAR2(50) NOT NULL,
        CONSTRAINT my_users_pk PRIMARY KEY (id)
);

INSERT INTO my_users (login, password) VALUES ('user1', 'pwd');
COMMIT;

CREATE OR REPLACE PROCEDURE get_user (user_cursor OUT SYS_REFCURSOR, loginn IN VARCHAR2,
                                    passwordd IN VARCHAR2)
    IS
BEGIN
    open user_cursor for
        SELECT login, password FROM my_users
        WHERE login = loginn AND password = passwordd;
END;